name: ğŸš€ Deploy website on push

on:
  push:
    branches:
      - main # branch name

jobs:
  web-deploy:
    name: ğŸ‰ Deploy Fullstack App
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ğŸ“¦ Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: ğŸ› ï¸ Build Frontend
      run: |
        cd frontendjs-vite
        npm install
        npm run build

    - name: ğŸ“‚ Deploy Frontend Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: shelly.o2switch.net
        username: zeri2011
        password: ${{ secrets.ftp_password }}
        local-dir: frontendjs-vite/dist/
        server-dir: public_html/

    - name: ğŸ“‚ Deploy Backend Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: shelly.o2switch.net
        username: zeri2011
        password: ${{ secrets.ftp_password }}
        local-dir: backend-fastapi/
        server-dir: backend/
